import com.twitter.scalding._

/* Goals: Find number of dashboards generated by a team
Keywords:
groupBy
size
sortBy, reverse, take
*/

class Dashboards(args:Args) extends Job(args) {
  val src = Tsv(args("input"), ('name, 'team))
  val sink = Tsv(args("result"))
  src.read
  .groupBy('team){ group =>
    group.size
  }
  .write(sink)
}

/* Task: Modify above program to do the following
  Reverse sort by number of dashboards & take the top 20
*/

